// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCircuitsCircuit = "circuits_circuit"

// CircuitsCircuit mapped from table <circuits_circuit>
type CircuitsCircuit struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	// Created           time.Time `gorm:"column:created" json:"created"`
	// LastUpdated       time.Time `gorm:"column:last_updated" json:"last_updated"`
	Cid               string    `gorm:"column:cid;not null" json:"cid"`
	// InstallDate       time.Time `gorm:"column:install_date" json:"install_date"`
	// CommitRate        int32     `gorm:"column:commit_rate" json:"commit_rate"`
	// Comments          string    `gorm:"column:comments;not null" json:"comments"`
	ProviderID        int64     `gorm:"column:provider_id;not null" json:"provider_id"`
	TypeID            int64     `gorm:"column:type_id;not null" json:"type_id"`
	TenantID          int64     `gorm:"column:tenant_id" json:"tenant_id"`
	// Description       string    `gorm:"column:description;not null" json:"description"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	// CustomFieldData   string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	TerminationAID    int64     `gorm:"column:termination_a_id" json:"termination_a_id" sql:"termination_a_id"`
	TerminationZID    int64     `gorm:"column:termination_z_id" json:"termination_z_id" sql:"termination_z_id"`
	// TerminationDate   time.Time `gorm:"column:termination_date" json:"termination_date"`
	// ProviderAccountID int64     `gorm:"column:provider_account_id" json:"provider_account_id"`
	Tags           []string            `sql:"-"`
	Provider       CircuitsProvider    `pg:"fk:provider_id"`
	Type           CircuitsCircuittype `pg:"fk:type_id"`
}

// TableName CircuitsCircuit's table name
func (*CircuitsCircuit) TableName() string {
	return TableNameCircuitsCircuit
}
