// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCircuitsCircuittermination = "circuits_circuittermination"

// CircuitsCircuittermination mapped from table <circuits_circuittermination>
type CircuitsCircuittermination struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	// TermSide          string    `gorm:"column:term_side;not null" json:"term_side"`
	// PortSpeed         int32     `gorm:"column:port_speed" json:"port_speed"`
	// UpstreamSpeed     int32     `gorm:"column:upstream_speed" json:"upstream_speed"`
	// XconnectID        string    `gorm:"column:xconnect_id;not null" json:"xconnect_id"`
	// PpInfo            string    `gorm:"column:pp_info;not null" json:"pp_info"`
	CircuitID         int64     `gorm:"column:circuit_id;not null" json:"circuit_id"`
	// SiteID            int64     `gorm:"column:site_id" json:"site_id"`
	// CableID           int64     `gorm:"column:cable_id" json:"cable_id"`
	// Description       string    `gorm:"column:description;not null" json:"description"`
	// Created           time.Time `gorm:"column:created" json:"created"`
	// LastUpdated       time.Time `gorm:"column:last_updated" json:"last_updated"`
	// MarkConnected     bool      `gorm:"column:mark_connected;not null" json:"mark_connected"`
	// ProviderNetworkID int64     `gorm:"column:provider_network_id" json:"provider_network_id"`
	// CustomFieldData   string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	// CableEnd          string    `gorm:"column:cable_end;not null" json:"cable_end"`
}

// TableName CircuitsCircuittermination's table name
func (*CircuitsCircuittermination) TableName() string {
	return TableNameCircuitsCircuittermination
}
