// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDcimCable = "dcim_cable"

// DcimCable mapped from table <dcim_cable>
type DcimCable struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	// Created         time.Time `gorm:"column:created" json:"created"`
	// LastUpdated     time.Time `gorm:"column:last_updated" json:"last_updated"`
	Type            string    `gorm:"column:type;not null" json:"type"`
	Status          string    `gorm:"column:status;not null" json:"status"`
	// Label           string    `gorm:"column:label;not null" json:"label"`
	// Color           string    `gorm:"column:color;not null" json:"color"`
	// Length          float64   `gorm:"column:length" json:"length"`
	// LengthUnit      string    `gorm:"column:length_unit;not null" json:"length_unit"`
	// AbsLength       float64   `gorm:"column:_abs_length" json:"_abs_length"`
	// CustomFieldData string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	TenantID        int64     `gorm:"column:tenant_id" json:"tenant_id"`
	// Comments        string    `gorm:"column:comments;not null" json:"comments"`
	// Description     string    `gorm:"column:description;not null" json:"description"``
	Terminations []*DcimCabletermination `pg:"fk:cable_id"`
}

// TableName DcimCable's table name
func (*DcimCable) TableName() string {
	return TableNameDcimCable
}
