// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDcimRearport = "dcim_rearport"

// DcimRearport mapped from table <dcim_rearport>
type DcimRearport struct {
	ID              int64     `gorm:"column:id;not null" json:"id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Type            string    `gorm:"column:type;not null" json:"type"`
	Positions       int16     `gorm:"column:positions;not null" json:"positions"`
	// Description     string    `gorm:"column:description;not null" json:"description"`
	DeviceID        int64     `gorm:"column:device_id;not null" json:"device_id"`
	// CableID         int64     `gorm:"column:cable_id" json:"cable_id"`
	// Name            string    `gorm:"column:_name;not null" json:"_name"`
	// Label           string    `gorm:"column:label;not null" json:"label"`
	// Created         time.Time `gorm:"column:created" json:"created"`
	// CustomFieldData string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	// LastUpdated     time.Time `gorm:"column:last_updated" json:"last_updated"`
	// MarkConnected   bool      `gorm:"column:mark_connected;not null" json:"mark_connected"`
	// Color           string    `gorm:"column:color;not null" json:"color"`
	// ModuleID        int64     `gorm:"column:module_id" json:"module_id"`
	// CableEnd        string    `gorm:"column:cable_end;not null" json:"cable_end"`
}

// TableName DcimRearport's table name
func (*DcimRearport) TableName() string {
	return TableNameDcimRearport
}
