// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDcimSite = "dcim_site"

// DcimSite mapped from table <dcim_site>
type DcimSite struct {
//	Created         time.Time `gorm:"column:created" json:"created"`
//	LastUpdated     time.Time `gorm:"column:last_updated" json:"last_updated"`
	CustomFieldData string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Slug            string    `gorm:"column:slug;not null" json:"slug"`
	Status          string    `gorm:"column:status;not null" json:"status"`
//	Facility        string    `gorm:"column:facility;not null" json:"facility"`
//	TimeZone        string    `gorm:"column:time_zone;not null" json:"time_zone"`
//	Description     string    `gorm:"column:description;not null" json:"description"`
//	PhysicalAddress string    `gorm:"column:physical_address;not null" json:"physical_address"`
//	ShippingAddress string    `gorm:"column:shipping_address;not null" json:"shipping_address"`
//	Latitude        float64   `gorm:"column:latitude" json:"latitude"`
//	Longitude       float64   `gorm:"column:longitude" json:"longitude"`
//	Comments        string    `gorm:"column:comments;not null" json:"comments"`
	GroupID         int64     `gorm:"column:group_id" json:"group_id"`
	RegionID        int64     `gorm:"column:region_id" json:"region_id"`
//	TenantID        int64     `gorm:"column:tenant_id" json:"tenant_id"`
}

// TableName DcimSite's table name
func (*DcimSite) TableName() string {
	return TableNameDcimSite
}
