// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDcimInterface = "dcim_interface"

// DcimInterface mapped from table <dcim_interface>
type DcimInterface struct {
	ID                 int64     `gorm:"column:id;not null" json:"id"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	Type               string    `gorm:"column:type;not null" json:"type"`
	MgmtOnly           bool      `gorm:"column:mgmt_only;not null" json:"mgmt_only"`
	// Description        string    `gorm:"column:description;not null" json:"description"`
	DeviceID           int64     `gorm:"column:device_id;not null" json:"device_id"`
	MacAddress         string    `gorm:"column:mac_address" json:"mac_address"`
	LagID              int64     `gorm:"column:lag_id" json:"lag_id"`
	// Enabled            bool      `gorm:"column:enabled;not null" json:"enabled"`
	// Mtu                int32     `gorm:"column:mtu" json:"mtu"`
	// Mode               string    `gorm:"column:mode;not null" json:"mode"`
	// UntaggedVlanID     int64     `gorm:"column:untagged_vlan_id" json:"untagged_vlan_id"`
	CableID            int64     `gorm:"column:cable_id" json:"cable_id"`
	//Name               string    `gorm:"column:_name;not null" json:"_name"`
	// Label              string    `gorm:"column:label;not null" json:"label"`
	//PathID             int64     `gorm:"column:_path_id" json:"_path_id"`
	// Created            time.Time `gorm:"column:created" json:"created"`
	// CustomFieldData    string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	// LastUpdated        time.Time `gorm:"column:last_updated" json:"last_updated"`
	// MarkConnected      bool      `gorm:"column:mark_connected;not null" json:"mark_connected"`
	ParentID           int64     `gorm:"column:parent_id" json:"parent_id"`
	// Wwn                string    `gorm:"column:wwn" json:"wwn"`
	// BridgeID           int64     `gorm:"column:bridge_id" json:"bridge_id"`
	// RfRole             string    `gorm:"column:rf_role;not null" json:"rf_role"`
	// RfChannel          string    `gorm:"column:rf_channel;not null" json:"rf_channel"`
	// RfChannelFrequency float64   `gorm:"column:rf_channel_frequency" json:"rf_channel_frequency"`
	// RfChannelWidth     float64   `gorm:"column:rf_channel_width" json:"rf_channel_width"`
	// TxPower            int16     `gorm:"column:tx_power" json:"tx_power"`
	// WirelessLinkID     int64     `gorm:"column:wireless_link_id" json:"wireless_link_id"`
	// ModuleID           int64     `gorm:"column:module_id" json:"module_id"`
	// VrfID              int64     `gorm:"column:vrf_id" json:"vrf_id"`
	// Duplex             string    `gorm:"column:duplex" json:"duplex"`
	Speed              int32     `gorm:"column:speed" json:"speed"`
	// PoeMode            string    `gorm:"column:poe_mode;not null" json:"poe_mode"`
	// PoeType            string    `gorm:"column:poe_type;not null" json:"poe_type"`
	// CableEnd           string    `gorm:"column:cable_end;not null" json:"cable_end"`
	Parent *DcimInterface `pg:"fk:parent_id"`
	Device DcimDevice     `pg:"fk:device_id"`
	LAG    *DcimInterface `pg:"fk:lag_id"`
	Tags   []string       `sql:"-"`
}

// TableName DcimInterface's table name
func (*DcimInterface) TableName() string {
	return TableNameDcimInterface
}
