// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDcimCabletermination = "dcim_cabletermination"

// DcimCabletermination mapped from table <dcim_cabletermination>
type DcimCabletermination struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CableEnd          string    `gorm:"column:cable_end;not null" json:"cable_end"`
	TerminationID     int64     `gorm:"column:termination_id;not null" json:"termination_id"`
	CableID           int64     `gorm:"column:cable_id;not null" json:"cable_id"`
	TerminationTypeID int32     `gorm:"column:termination_type_id;not null" json:"termination_type_id"`
	// DeviceID          int64     `gorm:"column:_device_id" json:"_device_id"`
	// RackID            int64     `gorm:"column:_rack_id" json:"_rack_id"`
	// LocationID        int64     `gorm:"column:_location_id" json:"_location_id"`
	// SiteID            int64     `gorm:"column:_site_id" json:"_site_id"`
	// Created           time.Time `gorm:"column:created" json:"created"`
	// LastUpdated       time.Time `gorm:"column:last_updated" json:"last_updated"`
}

// TableName DcimCabletermination's table name
func (*DcimCabletermination) TableName() string {
	return TableNameDcimCabletermination
}