// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDjangoContentType = "django_content_type"

// DjangoContentType mapped from table <django_content_type>
type DjangoContentType struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppLabel string `gorm:"column:app_label;not null" json:"app_label"`
	Model    string `gorm:"column:model;not null" json:"model"`
}

// TableName DjangoContentType's table name
func (*DjangoContentType) TableName() string {
	return TableNameDjangoContentType
}
