// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExtrasTaggeditem = "extras_taggeditem"

// ExtrasTaggeditem mapped from table <extras_taggeditem>
type ExtrasTaggeditem struct {
	ID            int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ObjectID      int32 `gorm:"column:object_id;not null" json:"object_id"`
	ContentTypeID int32 `gorm:"column:content_type_id;not null" json:"content_type_id"`
	TagID         int64 `gorm:"column:tag_id;not null" json:"tag_id"`
	Tag           ExtrasTag `pg:"fk:tag_id"`
}

// TableName ExtrasTaggeditem's table name
func (*ExtrasTaggeditem) TableName() string {
	return TableNameExtrasTaggeditem
}
