// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIpamIpaddress = "ipam_ipaddress"

// IpamIpaddress mapped from table <ipam_ipaddress>
type IpamIpaddress struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	// Created              time.Time `gorm:"column:created" json:"created"`
	// LastUpdated          time.Time `gorm:"column:last_updated" json:"last_updated"`
	Address              string    `gorm:"column:address;not null" json:"address"`
	// Description          string    `gorm:"column:description;not null" json:"description"`
	AssignedObjectID     int64     `gorm:"column:assigned_object_id" json:"assigned_object_id"`
	// NatInsideID          int64     `gorm:"column:nat_inside_id" json:"nat_inside_id"`
	// VrfID                int64     `gorm:"column:vrf_id" json:"vrf_id"`
	// TenantID             int64     `gorm:"column:tenant_id" json:"tenant_id"`
	// Status               string    `gorm:"column:status;not null" json:"status"`
	// Role                 string    `gorm:"column:role;not null" json:"role"`
	// DNSName              string    `gorm:"column:dns_name;not null" json:"dns_name"`
	AssignedObjectTypeID int32     `gorm:"column:assigned_object_type_id" json:"assigned_object_type_id"`
	CustomFieldData      string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	// Comments             string    `gorm:"column:comments;not null" json:"comments"`
}

// TableName IpamIpaddress's table name
func (*IpamIpaddress) TableName() string {
	return TableNameIpamIpaddress
}
