// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIpamPrefix = "ipam_prefix"

// IpamPrefix mapped from table <ipam_prefix>
type IpamPrefix struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	// Created         time.Time `gorm:"column:created" json:"created"`
	// LastUpdated     time.Time `gorm:"column:last_updated" json:"last_updated"`
	Prefix          string    `gorm:"column:prefix;not null" json:"prefix"`
	// Status          string    `gorm:"column:status;not null" json:"status"`
	// Description     string    `gorm:"column:description;not null" json:"description"`
	// RoleID          int64     `gorm:"column:role_id" json:"role_id"`
	// SiteID          int64     `gorm:"column:site_id" json:"site_id"`
	// VlanID          int64     `gorm:"column:vlan_id" json:"vlan_id"`
	// VrfID           int64     `gorm:"column:vrf_id" json:"vrf_id"`
	// TenantID        int64     `gorm:"column:tenant_id" json:"tenant_id"`
	// IsPool          bool      `gorm:"column:is_pool;not null" json:"is_pool"`
	// CustomFieldData string    `gorm:"column:custom_field_data;not null" json:"custom_field_data"`
	// Children        int64     `gorm:"column:_children;not null" json:"_children"`
	// Depth           int16     `gorm:"column:_depth;not null" json:"_depth"`
	// MarkUtilized    bool      `gorm:"column:mark_utilized;not null" json:"mark_utilized"`
	// Comments        string    `gorm:"column:comments;not null" json:"comments"`
	Tags []string `sql:"-"`
}

// TableName IpamPrefix's table name
func (*IpamPrefix) TableName() string {
	return TableNameIpamPrefix
}
